=== MegaLOD-project/arrowheads/MegaLOD/arrow_head.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="MegaLOD-project/arrow-heads/MegaLOD/arrow_head"
xmlns:ah="MegaLOD-project/arrow-heads/MegaLOD/arrow_head">

<element name="arrowheads" type="ah:typeArrowHeads"/>

<complexType name="typeArrowHeads">
    <sequence>
        <element name="arrowhead" type="ah:typeArrowHead" minOccurs="1" maxOccurs="unbounded"/>
    </sequence>
</complexType>

<complexType name="typeArrowHead">
    <sequence>
        <element name="order_number"/>
        <element name="group"/>
        <element name="type"/>
        <element name="sub_type"/>
        <element name="variant"/>
        <element name="raw_material" type="ah:typeRaw_Material"/>
        <element name="observations"/>
    </sequence>
    <attribute name="inventory_number"/>
</complexType>

<complexType name="typeRaw_Material">
    <sequence>
        <element name="typometry" type="ah:typeTypometry"/>
        <element name="morphology" type="ah:typeMorphology"/>
        <element name="retouch" type="ah:typeRetouch"/>
    </sequence>
</complexType>

<complexType name="typeTypometry">
    <sequence>
        <element name="lenght"/>
        <element name="width"/>
        <element name="thickness"/>
        <element name="body_lenght"/>
        <element name="base_lenght"/>
    </sequence>
</complexType>

<complexType name="typeMorphology">
    <sequence>
        <element name="point"/>
        <element name="body"/>
        <element name="base"/>
    </sequence>
</complexType>

<complexType name="typeRetouch">
    <sequence>
        <element name="mode"/>
        <element name="amplitude"/>
        <element name="direction"/>
        <element name="delineation"/>
        <element name="orientation"/>
        <element name="location"/>
        <element name="shape"/>
    </sequence>
</complexType>


</schema>

=== MegaLOD-project/arrowheads/MegaLOD/arrow_head2.xml
<?xml version="1.0" encoding="UTF-8"?>

<arrowhead xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="C:\Users\mark2\OneDrive\Ambiente de Trabalho\Projeto MegaLOD\arrow-heads\MegaLOD\arrow_head.xsd"
inventory_number="2">
    <order_number>2</order_number>
    <group>2</group>
    <type>Type2</type>
    <sub_type>false</sub_type>
    <variant>6</variant>
    <raw_material>
        <typometry>
            <lenght>22</lenght>
            <width>22.36</width>
            <thickness>5</thickness>
            <body_lenght>16</body_lenght>
            <base_lenght>6</base_lenght>
        </typometry>
        <morphology>
            <point>2</point>
            <body>6</body>
            <base>8</base>
        </morphology>
        <retouch>
            <mode>sas</mode>
            <amplitude>asdas</amplitude>
            <direction>asdasd</direction>
            <delineation>asdasd</delineation>
            <orientation>asdasd</orientation>
            <location>asdas</location>
            <shape>asdas</shape>
        </retouch>
    </raw_material>
    <observations>Ponta de Seta 2 de teste</observations>
    <image_url></image_url>
</arrowhead>
